stages:
 - build
 - test
 - post-test
 - release

include:
  - 'https://ci-files.skypicker.com/templates/build/coala.yml'
  - 'https://ci-files.skypicker.com/templates/build/tox_init.yml'
  - 'https://ci-files.skypicker.com/templates/build/zoo.yml'
  - 'https://ci-files.skypicker.com/templates/build/black.yml'

black:
  script:
    - black -l 120 --check --fast docs kw test setup.py
    - black -l 120 --check --py36 kw/cache/aio.py

tests:
  stage: test
  image: kiwicom/tox
  dependencies:
    - tox_init
  services:
   - redis
  script:
   - export TEST_REDIS_URL=redis://$REDIS_PORT_6379_TCP_ADDR
   - TOX_SKIP_ENV="coverage-report|coala" tox
  artifacts:
    paths:
      - reports/
      - .coverage*

tox_tests_coverage:
  extends: tests
  stage: post-test
  dependencies:
    - tox_init
    - tests
  needs:
    - tox_init
    - tests
  before_script:
    - mkdir -p $CI_PROJECT_DIR/coverage-reports
  artifacts:
    paths:
      - coverage-reports/
  script:
    - tox -e coverage-report -- -o $CI_PROJECT_DIR/coverage-reports/coverage-integration.xml

pages:
  stage: release
  image: python:3.7-alpine
  script:
   - apk add --no-cache make gcc build-base
   - pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt -e .
   - sphinx-apidoc --output-dir docs/kw --no-toc kw && make --directory=docs html
   - mv docs/_build/html public
  artifacts:
    paths:
     - public
  only:
   - master
