stages:
 - build
 - test
 - release

include:
  - 'https://ci-files.skypicker.com/templates/build/coala.yml'
  - 'https://ci-files.skypicker.com/templates/build/zoo.yml'

black:
  stage: build
  image: kiwicom/black:18.6b4
  script:
    - black -l 120 --check --fast docs kw test setup.py
    - black -l 120 --check --py36 kw/cache/aio.py

tests:
  stage: test
  image: kiwicom/tox
  services:
   - redis
  script:
   - export TEST_REDIS_URL=redis://$REDIS_PORT_6379_TCP_ADDR
   - tox

pages:
  stage: release
  image: python:3.5-alpine
  script:
   - apk add --no-cache make gcc build-base
   - pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt -e .
   - sphinx-apidoc --output-dir docs/kw --no-toc kw && make --directory=docs html
   - mv docs/_build/html public
  artifacts:
    paths:
     - public
  only:
   - master
