stages:
 - test
 - release

static-analysis:
  stage: test
  image: coala/base:0.11
  script:
   - coala --non-interactive

tests:
  stage: test
  image: themattrix/tox
  script:
   - tox
  cache:
    paths:
     - .tox/

release:
  stage: release
  image: python:3.5-alpine
  variables:
    PYPI_CONFIG: |
      [distutils]
      index-servers = kiwi

      [kiwi]
      repository: https://pypi.skypicker.com/pypi/
      username: $PYPI_USERNAME
      password: $PYPI_PASSWORD
  script:
   - echo "$PYPI_CONFIG" > ~/.pypirc
   - pip install wheel
   - python setup.py bdist_wheel --universal upload -r kiwi
  only:
   - master
  allow_failure: yes  # always runs but fails if there's already a release for the version

pages:
  stage: release
  image: python:3.5-alpine
  script:
   - apk add --no-cache make
   - pip install -r requirements.txt -r test-requirements.txt -r docs-requirements.txt -e .
   - sphinx-apidoc --output-dir docs/kw --no-toc kw && make --directory=docs html
   - mv docs/_build/html public
  artifacts:
    paths:
     - public
  only:
   - master
